### ISSUE TITLE
Eliminate unhandled promise rejection warnings from navbar.test.js and routes.test.js

### ISSUE THREAD

**Issue by ibeckermayer** [covidwatchorg/portal#474]
```jest
 PASS  client/__tests__/navbar.test.js
  NavBar
    ✓ renders correctly (148 ms)
    ✓ has 3 MenuItems for a non-admin (70 ms)
    ✓ has 5 MenuItems for an admin (98 ms)
    ✓ logs out a user when they click Log Out (106 ms)

(node:1921) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'createElement' of undefined
    at new file (/Users/ibeckermayer/covid19risk/permission-portal/frontend/node_modules/jsdom/lib/jsdom/browser/Window.js:532:34)
    at file (/Users/ibeckermayer/covid19risk/permission-portal/frontend/node_modules/browser-image-compression/lib/utils.js:66:5)
    at new Promise (<anonymous>)
    at img (/Users/ibeckermayer/covid19risk/permission-portal/frontend/node_modules/browser-image-compression/lib/utils.js:66:5)
    at /Users/ibeckermayer/covid19risk/permission-portal/frontend/node_modules/browser-image-compression/lib/utils.js:124:11
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1921) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1921) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 PASS  client/__tests__/footer.test.js
  Footer
    ✓ renders correctly (64 ms)
    ✓ has a valid 'privacy policy' link (538 ms)
    ✓ has a valid 'support' link (165 ms)

 PASS  client/__tests__/routes.test.js
  Routes
    ✓ redirects to 404 for invalid link (178 ms)
    ✓ shows Login if user not signed in (66 ms)
    ✓ shows CodeValidations if non-admin user goes to admin-only route (341 ms)
    ✓ shows ChangePasswordModal on first login (210 ms)

(node:1920) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'createElement' of undefined
    at new file (/Users/ibeckermayer/covid19risk/permission-portal/frontend/node_modules/jsdom/lib/jsdom/browser/Window.js:532:34)
    at file (/Users/ibeckermayer/covid19risk/permission-portal/frontend/node_modules/browser-image-compression/lib/utils.js:66:5)
    at new Promise (<anonymous>)
    at img (/Users/ibeckermayer/covid19risk/permission-portal/frontend/node_modules/browser-image-compression/lib/utils.js:66:5)
    at /Users/ibeckermayer/covid19risk/permission-portal/frontend/node_modules/browser-image-compression/lib/utils.js:124:11
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1920) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1920) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by colbymorrison** [comment]
I think we can close this.

**Comment by ibeckermayer** [comment]
Closed by https://github.com/covidwatchorg/portal/pull/446/commits/12eafe2ddc41084984ac9741723e0eaa5f6e802b
